DROP TABLE IF EXISTS PEOPLE;
CREATE TABLE IF NOT EXISTS PEOPLE
(
    id           VACHAR(50) PRIMARY KEY,
    nick_name    VARCHAR(50) NOT NULL,
    profile_path VARCHAR(100)
);

DROP TABLE IF EXISTS POST;
CREATE TABLE IF NOT EXISTS POST
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    content    VARCHAR(100) NOT NULL,
    writer     VACHAR(50)   NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    hash_code  INTEGER      NOT NULl,
    FOREIGN KEY (writer) REFERENCES PEOPLE (id)
);

DROP TABLE IF EXISTS COMMENT;
CREATE TABLE IF NOT EXISTS COMMENT
(
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    content    VARCHAR(100) NOT NULL,
    writer     VACHAR(50)   NOT NULL,
    post_id    INTEGER      NOT NULL,
    created_at TIMESTAMP    NOT NULL,
    FOREIGN KEY (writer) REFERENCES PEOPLE (id),
    FOREIGN KEY (post_id) REFERENCES POST (id)
);

DROP TABLE IF EXISTS LOCATION;
CREATE TABLE IF NOT EXISTS LOCATION
(
    name       VARCHAR(100) PRIMARY KEY,
    link       VARCHAR(200) NOT NULL,
    image_path VARCHAR(100) NOT NULL,
    post_id    INTEGER      NOT NULL,
    FOREIGN KEY (post_id) REFERENCES POST (id)
);

DROP TABLE IF EXISTS IMAGE;
CREATE TABLE IF NOT EXISTS IMAGE
(
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    original  VARCHAR(100) NOT NULL,
    thumbnail VARCHAR(100) NOT NULL,
    post_id   INTEGER      NOT NULL,
    FOREIGN KEY (post_id) REFERENCES POST (id)
);

DROP TABLE IF EXISTS EMBED;
CREATE TABLE IF NOT EXISTS EMBED
(
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    src       VARCHAR(100) NOT NULL,
    thumbnail VARCHAR(100) NOT NULL,
    post_id   INTEGER      NOT NULL,
    FOREIGN KEY (post_id) REFERENCES POST (id)
);

DROP TABLE IF EXISTS TAG;
CREATE TABLE IF NOT EXISTS TAG
(
    id VARCHAR(30) PRIMARY KEY
);

DROP TABLE IF EXISTS POST_TAG;
CREATE TABLE IF NOT EXISTS POST_TAG
(
    post_id LONG        NOT NULL,
    tag_id  VARCHAR(30) NOT NULL,
    FOREIGN KEY (post_id) REFERENCES POST (id),
    FOREIGN KEY (tag_id) REFERENCES TAG (id)
);